name: CI Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Frontend Image
        run: |
          IMAGE_ID=ghcr.io/${{ secrets.GHCR_USERNAME }}/recruitment-frontend
          docker build -t $IMAGE_ID:latest .
          docker push $IMAGE_ID:latest

      - name: Trigger CD workflow in deployment repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CD_TRIGGER_PAT }}
          repository: bavindushan/recruitment-system-deployment
          event-type: deploy-frontend
          client-payload: '{"service": "frontend"}'

